### ISSUE TITLE
Discuss pros and cons in README

### ISSUE THREAD

**Issue by kevinmickey** [rparent/django-lock-tokens#1]
It would be nice to understand the pros and cons of this package's token-based approach relative to other approaches (saxix/django-concurrency and gavinwahl/django-optimistic-lock).

See, e.g.,the discussion at https://github.com/gavinwahl/django-optimistic-lock#comparison-to-django-concurrency

Thanks!

**Comment by rparent** [comment]
That's a good idea, I will add some explanations to the `README` file.
To answer quickly, here are some advantages of the package:

1) No need to modify your models to use the locking mechanism : you don't "pollute" your datamodel with "non-data" fields. This also means you can use the locking mechanism on third party models that cannot be modified.
2) No need to use sessions (but you can still use it if you need).
3) Mechanism to check that an object is locked BEFORE trying to modify it.
4) Rest API (+ javascript client to use it) out-of-the-box.
5) Admin interface integration

Of course the packages you mention also cover some of those points, but I could not find any package that covers all of them at once.
This package was originally developed to prevent concurrency editing of complex objects via a web interface using AJAX calls. This can help you understand what kind of issues the package tries to resolve!
