### ISSUE TITLE
Getting it to work with custom change_form.html template

### ISSUE THREAD

**Issue by BrendaH** [rparent/django-lock-tokens#4]
* django-lock-tokens version: 0.1.4
* Django version: 1.11.15
* Python version: 3.5
* Operating System: Windows 10

### Description & What I Did

I'm trying to use `LockableModelAdmin` for one of my models (extends `LockableModel`) but since I am using a custom `change_form.html` template I'm getting some unexpected results. My `change_form.html` is basically a complete rebuild of the original `admin/change_form.html`.
My whole installment/setup is complete. My modified `change_form.html` extends the `admin/lock_tokens_change_form.html` and I am passing the extra_context to the page (where the lock_token is added) but when I call `{{block.super}}` I also get some stuff from Django's own `{{ block content }}` that I do not want or need. Like an extra history button, an extra form tag, etc. When trying to save (getting the save buttons on the required spot is also a bit of a hassle) I get the message "data ManagementForm are missing or have been tampered with". All csrf tokens are in place (and some extra, perhaps that is the issue here...)

This setup works great for a normal model admin without custom templates, but for this case it would be nice if I could just include a template tag to just get all the necessary javascript from django-lock-tokens and do the checking on the presence of lock_token for the submit buttons in my own custom template.

**Suggestion / feature request**
A simple tag to include the necessary javascript in a custom template.

**Comment by BrendaH** [comment]
Or would it be better if I do all the locking manually, since I also have custom views (even though it's in the admin)? (going to try that route now... )
It would still be nice to notify people that hugely modified custom templates might not work well and a different approach (locking/unlocking 'manually') might be needed.

**Comment by rparent** [comment]
I agree that something is missing when you want to use your own custom templates in the admin site. 

A template tag could be a good idea, or at least add a javascript function that does the work needed in the admin site, and some documentation about it.
